/* Banque de questions du QCM (semaines 1 à 7 + méthodes) */
const ALL_QUESTIONS = [
  // ================== SEMAINE 1 ==================
  {wk:'s1', topic:'Arguments du main', q:'Dans <code>public static void main(String[] args)</code>, quel est le type de <code>args</code> ?',
   choices:['Un tableau de <code>String</code>','Une seule <code>String</code>','Un tableau de <code>int</code>','Un objet <code>Scanner</code>'],
   c:0, exp:'<code>String[] args</code> est un <b>tableau de String</b>.'},
  {wk:'s1', topic:'Conversion', q:'Pour convertir <code>"42"</code> en <code>int</code> :',
   choices:['<code>(int) "42"</code>','<code>Integer.parseInt("42")</code>','<code>String.toInt("42")</code>','<code>"42".toInt()</code>'],
   c:1, exp:'<code>Integer.parseInt(s)</code> convertit une chaîne en int.'},
  {wk:'s1', topic:'Type de retour', q:'Le code compile-t-il ? <code>public boolean flag() { return 0; }</code>',
   choices:['Oui, 0 → false','Oui, 0 → true','Non, erreur de compilation','Oui mais exception'],
   c:2, exp:'<code>int</code> et <code>boolean</code> ne sont pas compatibles.'},
  {wk:'s1', topic:'void et return', q:'<code>public void piaf() { return; }</code> est-il valide ?',
   choices:['Non, void ne peut jamais avoir return','Oui, ça sort de la méthode','Non, il faut return null','Oui, mais en dernière ligne uniquement'],
   c:1, exp:'<code>return;</code> sans valeur est autorisé dans une void pour sortir plus tôt.'},
  {wk:'s1', topic:'Appel de méthode', q:'La bonne façon d\'appeler nextInt :',
   choices:['<code>clavier.nextInt</code>','<code>clavier.nextInt()</code>','<code>Scanner.nextInt</code>','<code>nextInt(clavier)</code>'],
   c:1, exp:'Un appel de méthode a toujours des parenthèses.'},
  {wk:'s1', topic:'Scanner', q:'Pour lire un nombre à virgule :',
   choices:['<code>nextInt()</code>','<code>nextLine()</code>','<code>nextDouble()</code>','<code>readFloat()</code>'],
   c:2, exp:'<code>nextDouble()</code> pour double, <code>nextFloat()</code> pour float.'},
  {wk:'s1', topic:'static', q:'<code>static int i=10;</code> Après <code>s2.i++;</code>, que vaut <code>s1.i</code> ?',
   choices:['10','11','0','Erreur'],
   c:1, exp:'Un champ static est partagé par tous les objets — une seule copie.'},
  {wk:'s1', topic:'final', q:'<code>final String NOM="X"; s1.NOM="Y";</code> — que se passe-t-il ?',
   choices:['OK','Exception à l\'exécution','Erreur de compilation','OK dans main seulement'],
   c:2, exp:'<code>final</code> = une seule affectation, à la déclaration ou au constructeur.'},
  {wk:'s1', topic:'String', q:'<code>String a="hi"; String b=new String("hi");</code>',
   choices:['a=null','Contenus identiques, mais a==b peut être false','b contient "new hi"','a==b toujours true'],
   c:1, exp:'Deux objets différents mais contenus identiques. Utiliser <code>.equals()</code>.'},
  {wk:'s1', topic:'Comparaison String', q:'Pour comparer le contenu de deux String :',
   choices:['<code>a == b</code>','<code>a.equals(b)</code>','<code>a.compareTo(b)</code>','<code>String.compare(a,b)</code>'],
   c:1, exp:'<code>.equals()</code> compare le contenu, <code>==</code> compare les adresses.'},
  {wk:'s1', topic:'Déclaration multiple', q:'Après <code>int d[], e;</code>, d et e sont :',
   choices:['Deux tableaux d\'int','d tableau, e int simple','Deux int simples','Erreur'],
   c:1, exp:'Les <code>[]</code> collent au nom de la variable, pas au type.'},
  {wk:'s1', topic:'Allocation tableau', q:'<code>double[] notes; notes[0]=12.5;</code> — que se passe-t-il ?',
   choices:['notes[0]=12.5','notes[0]=0.0','NullPointerException','ArrayIndexOutOfBoundsException'],
   c:2, exp:'Tableau déclaré mais pas alloué (pas de <code>new</code>) = null → NPE.'},
  {wk:'s1', topic:'Taille tableau', q:'Pour la taille d\'un tableau <code>a</code> :',
   choices:['<code>a.length()</code>','<code>a.size()</code>','<code>a.length</code>','<code>length(a)</code>'],
   c:2, exp:'<code>length</code> est un attribut (pas de parenthèses) pour un tableau. Pour String c\'est <code>s.length()</code>.'},
  {wk:'s1', topic:'Valeurs par défaut', q:'Après <code>int[] a = new int[3];</code>, a contient :',
   choices:['[null,null,null]','[0,0,0]','Rien','Aléatoire'],
   c:1, exp:'Java initialise à 0 pour les entiers.'},
  {wk:'s1', topic:'Dépassement', q:'<code>double[] t = new double[3]; for(int i=0;i&lt;=3;i++) t[i]=i;</code>',
   choices:['OK','Erreur compilation','ArrayIndexOutOfBoundsException','NullPointerException'],
   c:2, exp:'Indices valides 0,1,2. <code>i&lt;=3</code> accède à t[3] → exception.'},
  {wk:'s1', topic:'Tableaux 2D', q:'Pour parcourir un tableau 2D :',
   choices:['Une seule boucle','Deux boucles imbriquées','<code>println(tab)</code>','Convertir en 1D'],
   c:1, exp:'Boucle externe = lignes, boucle interne = colonnes.'},
  {wk:'s1', topic:'Référence tableau', q:'<code>int[][] tab3 = tab; tab3[0][0]=99;</code>',
   choices:['tab inchangé','tab et tab3 valent 99','Erreur compilation','tab3 est une copie'],
   c:1, exp:'On copie la référence, pas le contenu. Même tableau en mémoire.'},
  {wk:'s1', topic:'Instanciation', q:'<code>new Train()</code> fait :',
   choices:['Déclare uniquement','Alloue + constructeur + retourne référence','Appelle main','Copie'],
   c:1, exp:'3 étapes : allocation mémoire, constructeur, référence retournée.'},
  {wk:'s1', topic:'Appel de méthode', q:'Pour appeler <code>stopper()</code> sur <code>trainsdi</code> :',
   choices:['<code>stopper(trainsdi)</code>','<code>Train.stopper()</code>','<code>trainsdi.stopper()</code>','<code>trainsdi::stopper</code>'],
   c:2, exp:'Syntaxe : <code>nomObjet.nomMethode(args)</code>.'},
  {wk:'s1', topic:'Attribut vs méthode', q:'<code>a.length</code> et <code>s.stopper()</code> diffèrent parce que :',
   choices:['Interchangeables','length attribut, stopper méthode','length privé','stopper() erroné'],
   c:1, exp:'Attribut sans (), méthode avec (). Piège classique.'},

  // ================== SEMAINE 2 ==================
  {wk:'s2', topic:'Héritage', q:'Quel mot-clé déclare que Fille hérite de Mere ?',
   choices:['<code>inherits</code>','<code>extends</code>','<code>implements</code>','<code>super</code>'],
   c:1, exp:'<code>extends</code> pour l\'héritage. <code>implements</code> pour les interfaces (semaine 4).'},
  {wk:'s2', topic:'super(...)', q:'Dans un constructeur fille, <code>super(...)</code> doit être :',
   choices:['N\'importe où','La 1ère ligne','La dernière ligne','Optionnel toujours'],
   c:1, exp:'<code>super(...)</code> DOIT être la 1ère instruction du constructeur.'},
  {wk:'s2', topic:'protected', q:'Un attribut <code>protected int i;</code> est accessible :',
   choices:['Seulement dans la classe','Dans la classe + ses sous-classes + le package','Partout','Nulle part'],
   c:1, exp:'<code>protected</code> = classe + sous-classes + même package.'},
  {wk:'s2', topic:'Constructeur auto', q:'Si la classe parent n\'a que <code>Parent(int x)</code>, dans la fille :',
   choices:['<code>super()</code> est ajouté auto','Il faut explicitement <code>super(x)</code>','Aucun constructeur nécessaire','Erreur au runtime'],
   c:1, exp:'Sans <code>Parent()</code>, l\'appel implicite <code>super()</code> échoue. On doit appeler <code>super(x)</code>.'},
  {wk:'s2', topic:'this vs super', q:'Peut-on avoir <code>this(...)</code> ET <code>super(...)</code> dans un constructeur ?',
   choices:['Oui','Non, un seul des deux','Oui mais dans cet ordre','Oui si static'],
   c:1, exp:'Les deux doivent être en 1ère ligne, donc incompatibles.'},
  {wk:'s2', topic:'Agrégation', q:'Le code <code>class Config { Ecran e; }</code> représente :',
   choices:['Héritage','Agrégation','Dépendance','Association'],
   c:1, exp:'Un objet Ecran stocké en attribut = agrégation.'},
  {wk:'s2', topic:'Dépendance', q:'<code>void manger(Os unOs) { }</code> représente :',
   choices:['Héritage','Agrégation','Dépendance','Association'],
   c:2, exp:'L\'objet Os est reçu en paramètre mais pas stocké → dépendance.'},
  {wk:'s2', topic:'Upcasting', q:'<code>Personne p = new Homme();</code> nécessite un cast ?',
   choices:['Oui, <code>(Personne)</code>','Non, implicite (fille → mère)','Non, on ne peut pas','Oui, <code>(Homme)</code>'],
   c:1, exp:'Upcasting = implicite. Un Homme EST une Personne.'},
  {wk:'s2', topic:'Downcasting', q:'<code>Personne p = new Personne(); Homme h = (Homme) p;</code>',
   choices:['Compile et marche','Compile puis ClassCastException','Erreur de compilation','Retourne null'],
   c:1, exp:'Compile car cast présent, mais explose à l\'exécution.'},
  {wk:'s2', topic:'super.methode()', q:'Pour appeler la méthode <code>afficher()</code> du parent dans la fille :',
   choices:['<code>parent.afficher()</code>','<code>super.afficher()</code>','<code>super().afficher()</code>','<code>this.super()</code>'],
   c:1, exp:'<code>super.methode()</code> — sans parenthèses après super.'},
  {wk:'s2', topic:'@Override', q:'À quoi sert <code>@Override</code> ?',
   choices:['Rendre la méthode plus rapide','Indiquer une redéfinition d\'une méthode héritée','Rendre static','Bloquer l\'héritage'],
   c:1, exp:'C\'est une annotation qui indique une redéfinition. Le compilateur vérifie que la signature correspond bien à une méthode du parent.'},
  {wk:'s2', topic:'Exception perso', q:'Pour créer une exception personnalisée :',
   choices:['<code>class E implements Exception</code>','<code>class E extends Exception</code>','<code>class E throws Exception</code>','<code>@Exception class E</code>'],
   c:1, exp:'Une exception est une classe qui hérite de Exception.'},
  {wk:'s2', topic:'throws', q:'<code>public void f() throws IOException</code> signifie :',
   choices:['La méthode lève toujours IOException','La méthode peut lever IOException','Elle capture IOException','Elle refuse IOException'],
   c:1, exp:'<code>throws</code> déclare que la méthode PEUT lancer cette exception.'},
  {wk:'s2', topic:'Héritage privé', q:'Un attribut <code>private int x</code> du parent est accessible dans la fille ?',
   choices:['Directement','Via une méthode publique/protected héritée','Pas du tout','Via cast'],
   c:1, exp:'private est invisible dans la fille. On passe par des méthodes publiques.'},
  {wk:'s2', topic:'Association', q:'Une classe <code>Mariage { Homme h; Femme f; date; lieu; }</code> représente :',
   choices:['Héritage','Agrégation simple','Association avec classe intermédiaire','Dépendance'],
   c:2, exp:'La relation elle-même a des attributs (date, lieu), d\'où la classe intermédiaire.'},

  // ================== SEMAINE 3 ==================
  {wk:'s3', topic:'this()', q:'Où doit être placé <code>this(...)</code> dans un constructeur ?',
   choices:['N\'importe où','La 1ère ligne, comme super(...)','La dernière ligne','Dans une méthode static'],
   c:1, exp:'Comme super(...), this(...) doit être la toute 1ère instruction du constructeur.'},
  {wk:'s3', topic:'this vs super', q:'Peut-on écrire this(...) ET super(...) dans le même constructeur ?',
   choices:['Oui, dans cet ordre','Non, un seul des deux','Oui, dans n\'importe quel ordre','Oui si static'],
   c:1, exp:'Les deux doivent être en 1ère ligne, donc ils sont incompatibles entre eux.'},
  {wk:'s3', topic:'toString()', q:'Que se passe-t-il quand on fait <code>System.out.println(monObjet)</code> ?',
   choices:['Erreur de compilation sans toString()','Java appelle automatiquement toString()','Affiche toujours l\'adresse mémoire','Il faut appeler .afficher() à la main'],
   c:1, exp:'println() appelle automatiquement toString() sur l\'objet pour savoir quoi afficher.'},
  {wk:'s3', topic:'equals()', q:'Sans redéfinition, que compare <code>a.equals(b)</code> sur 2 objets ?',
   choices:['Le contenu des attributs','Les références (comme ==)','Toujours true','Toujours false'],
   c:1, exp:'equals() hérité d\'Object compare les références par défaut, comme ==.'},
  {wk:'s3', topic:'Affectation d\'objets', q:'Après <code>Point a = new Point(1,1); Point b = new Point(9,9); a = b;</code>, que devient l\'ancien contenu de a (1,1) ?',
   choices:['Fusionné avec b','Toujours accessible via a','Perdu, inaccessible','Copié dans une variable temporaire'],
   c:2, exp:'a = b copie la référence. L\'ancien objet (1,1) n\'a plus aucune variable qui pointe vers lui.'},
  {wk:'s3', topic:'Surcharge constructeur', q:'Qu\'est-ce qui distingue 2 constructeurs surchargés ?',
   choices:['Leur nom','Leur signature (nombre/type de paramètres)','Leur type de retour','Leur ordre dans le fichier'],
   c:1, exp:'Même nom (celui de la classe) obligatoire, mais signatures différentes.'},
  {wk:'s3', topic:'package', q:'Où doit être placée l\'instruction <code>package nom;</code> ?',
   choices:['N\'importe où dans le fichier','En 1ère ligne du fichier','Après les imports','Dans le main uniquement'],
   c:1, exp:'package est toujours la première ligne du fichier, avant les imports.'},
  {wk:'s3', topic:'import', q:'Pourquoi <code>import transport.*;</code> est nécessaire dans Conducteur.java ?',
   choices:['Pour utiliser la classe Train, d\'un autre package','Pour hériter de Train','Obligatoire même dans le même package','Ce n\'est jamais nécessaire'],
   c:0, exp:'Sans import, une classe d\'un autre package est invisible, même si elle est public.'},
  {wk:'s3', topic:'protected', q:'Un attribut protected est visible depuis :',
   choices:['Uniquement sa classe','Sa classe + ses sous-classes (+ même package)','Partout sans restriction','Aucune classe externe'],
   c:1, exp:'protected = classe + sous-classes + même package. Plus large que private, plus restreint que public.'},
  {wk:'s3', topic:'Surcharge méthode', q:'<code>Point.translater(int,int)</code> et <code>Segment.translater(Point,Point)</code> : que représente ce même nom ?',
   choices:['Une erreur de compilation','De la surcharge de méthode','De l\'héritage','De la composition'],
   c:1, exp:'Même nom, signatures différentes (types de paramètres) = surcharge, pas un conflit.'},
  {wk:'s3', topic:'this — retour de référence', q:'Que retourne <code>public Point getReferenceToMe() { return this; }</code> ?',
   choices:['Une copie du point','Rien, erreur','Une référence vers l\'objet courant lui-même','null'],
   c:2, exp:'this désigne l\'objet courant ; le retourner permet à l\'appelant d\'obtenir une référence vers CET objet précis.'},
  {wk:'s3', topic:'Masquage (shadowing)', q:'Dans un constructeur, une variable locale du même nom qu\'un attribut fait quoi sans this. ?',
   choices:['Provoque une erreur de compilation','Masque (éclipse) l\'attribut','Fusionne avec l\'attribut','Rien, this. est toujours implicite'],
   c:1, exp:'La variable locale la plus proche masque l\'attribut. this.nom force à viser l\'attribut.'},
  {wk:'s3', topic:'getClass()', q:'Que fait <code>a.getClass().equals(b.getClass())</code> ?',
   choices:['Compare le contenu de a et b','Compare si a et b sont la même instance','Compare si a et b sont de la même classe (type)','Erreur de compilation'],
   c:2, exp:'getClass() retourne le type réel de l\'objet ; on compare ici les TYPES, pas le contenu ni l\'identité.'},
  {wk:'s3', topic:'super cross-package', q:'Dans Conducteur (package individu) qui extends Personne (package individu), l\'appel super(pnom) fonctionne :',
   choices:['Seulement si même package','Même entre packages différents, tant que l\'héritage est déclaré','Jamais entre packages','Seulement avec import explicite de super'],
   c:1, exp:'L\'héritage fonctionne normalement entre packages différents (ex: Conducteur du package individu pourrait hériter d\'une classe d\'un autre package).'},
  {wk:'s3', topic:'Agrégation Segment/Point', q:'<code>class Segment { public Point p1, p2; ... }</code> représente quelle relation ?',
   choices:['Héritage','Agrégation (Segment contient des Point)','Dépendance','Généralisation'],
   c:1, exp:'2 attributs de type Point dans Segment = agrégation, les Point existent indépendamment (créés avant, passés au constructeur).'},
  // ================== SEMAINE 4 ==================
  {wk:'s4', topic:'Classe abstraite', q:'<code>public abstract class Personnels { public abstract void travailler(int h); }</code>. Que fait <code>new Personnels()</code> ?',
   choices:['Crée un objet Personnels vide','Erreur de compilation : classe abstraite non instanciable','Crée un objet Enseignants par défaut','Lance une exception à l\'exécution'],
   c:1, exp:'Une classe abstraite ne peut jamais être instanciée directement. Il faut passer par une fille concrète : new Enseignants().'},
  {wk:'s4', topic:'Méthode abstraite', q:'Qu\'est-ce qui distingue une méthode abstraite d\'une méthode normale ?',
   choices:['Elle est private','Elle n\'a pas de corps, se termine par ;','Elle est static','Elle retourne toujours null'],
   c:1, exp:'Une méthode abstract n\'a pas de {} — elle finit par ; et force chaque sous-classe concrète à la redéfinir.'},
  {wk:'s4', topic:'interface', q:'Une <code>interface</code> peut contenir :',
   choices:['Des attributs d\'état et un constructeur','Uniquement des signatures de méthodes publiques','Uniquement des méthodes private','Aucune méthode, juste des constantes'],
   c:1, exp:'Une interface (avant Java 8) = pur contrat : uniquement des signatures publiques, pas de corps, pas de constructeur, pas d\'attribut d\'état.'},
  {wk:'s4', topic:'implements multiple', q:'<code>class Personne implements Client, Employe, Sportif</code>. Que doit fournir Personne ?',
   choices:['Uniquement les méthodes de Client','Toutes les méthodes des 3 interfaces','Aucune, tout est hérité','Un constructeur par interface'],
   c:1, exp:'implements = promesse de fournir TOUTES les méthodes de TOUTES les interfaces listées. Sinon, erreur de compilation.'},
  {wk:'s4', topic:'extends vs implements', q:'Une classe Java peut :',
   choices:['extends plusieurs classes','implements une seule interface','extends une seule classe + implements plusieurs interfaces','extends plusieurs interfaces'],
   c:2, exp:'Java autorise UN SEUL extends (héritage simple) mais PLUSIEURS implements. C\'est la solution Java à l\'héritage multiple.'},
  {wk:'s4', topic:'Polymorphisme d\'exécution', q:'<code>Instrument i = new Wind(); i.play(0);</code> où Wind redéfinit play(). Quelle version est appelée ?',
   choices:['Instrument.play() (type déclaré)','Wind.play() (classe réelle de l\'objet)','Les deux','Erreur de compilation'],
   c:1, exp:'Le polymorphisme d\'exécution : c\'est la CLASSE RÉELLE de l\'objet qui détermine la méthode appelée, pas le type de la variable.'},
  {wk:'s4', topic:'Argument polymorphe', q:'<code>static void tune(Instrument i) { i.play(0); }</code>. Cette méthode accepte :',
   choices:['Uniquement des Instrument','Instrument et toutes ses filles (Wind, Brass...)','Uniquement Wind','Aucun type précis'],
   c:1, exp:'Un paramètre du type parent accepte n\'importe quelle sous-classe : c\'est un argument polymorphe.'},
  {wk:'s4', topic:'List / Vector', q:'<code>List&lt;Forme&gt; l = new Vector&lt;Forme&gt;();</code>. Pourquoi le type d\'accueil est List et pas Vector ?',
   choices:['Obligatoire, sinon erreur','Bonne pratique : programmer contre l\'interface, pas l\'implémentation','Vector est plus rapide comme type déclaré','Pour cacher le contenu'],
   c:1, exp:'Programmer contre List (l\'interface) permet de changer d\'implémentation (ArrayList, LinkedList...) sans toucher au reste du code.'},
  {wk:'s4', topic:'Comparable', q:'Pour utiliser <code>Collections.sort(l)</code> sur une <code>List&lt;Forme&gt;</code>, il faut :',
   choices:['Rien, ça marche toujours','Que Forme implémente Comparable&lt;Forme&gt; avec compareTo()','Que Forme extends Comparator','Utiliser un tableau à la place'],
   c:1, exp:'sort() sans comparateur utilise l\'ordre naturel, défini via compareTo() dans l\'interface Comparable.'},
  {wk:'s4', topic:'Comparator', q:'<code>Collections.sort(l, FormeComparator.SURFACE_ORDER)</code>. À quoi sert le 2ème argument ?',
   choices:['À filtrer la liste','À définir un ordre externe (par surface) différent de l\'ordre naturel','À accélérer le tri','Il est ignoré'],
   c:1, exp:'Un Comparator fournit un ordre ALTERNATIF au compareTo() naturel. Ici, tri par surface au lieu de la distance à l\'origine.'},
  // ================== MÉTHODES ==================
  {wk:'meth', topic:'Trace — ordre des constructeurs', q:'<code>new Chien("Max")</code> où <code>Chien extends Animal</code>. Dans quel ordre s\'exécutent les constructeurs ?',
   choices:['Chien puis Animal','Animal puis Chien','Seulement Chien','Seulement Animal'],
   c:1, exp:'<code>super(...)</code> (explicite ou implicite) exécute le constructeur du parent AVANT le reste du constructeur de la fille.'},
  {wk:'meth', topic:'Trace — méthode redéfinie', q:'<code>Animal y = new Chien("Max"); y.crier();</code> avec <code>crier()</code> redéfinie dans Chien. Quelle version s\'exécute ?',
   choices:['Celle d\'Animal (type déclaré)','Celle de Chien (classe réelle de l\'objet)','Les deux','Erreur de compilation'],
   c:1, exp:'Polymorphisme : la méthode appelée dépend de la classe réelle de l\'objet, pas du type de la variable.'},
  {wk:'meth', topic:'Trace — static', q:'Un attribut <code>static int compteur</code> incrémenté dans le constructeur d\'Animal. Après <code>new Animal("a"); new Chien("b");</code> il vaut :',
   choices:['1','2','0','3'],
   c:1, exp:'Le constructeur de Chien appelle celui d\'Animal via super : deux incrémentations, une seule case partagée.'},
  {wk:'meth', topic:'Compilation — constructeur', q:'<code>public void Rectangle(double l, double h) { ... }</code> dans la classe Rectangle est :',
   choices:['Un constructeur valide','Une méthode nommée Rectangle, pas un constructeur','Une erreur de compilation','Un constructeur static'],
   c:1, exp:'Un constructeur n\'a JAMAIS de type de retour. Avec void, c\'est une méthode ordinaire, et new Rectangle(3,4) ne trouve aucun constructeur à 2 paramètres.'},
  {wk:'meth', topic:'Compilation — message', q:'Le compilateur affiche <code>non-static method aire() cannot be referenced from a static context</code>. Cause :',
   choices:['aire() est private','On appelle aire() depuis main sans objet','Il manque un return','aire() n\'existe pas'],
   c:1, exp:'Depuis main (static), une méthode d\'instance doit être appelée sur un objet : <code>r.aire()</code>.'},
  {wk:'meth', topic:'Exécution — NPE', q:'<code>Rectangle[] t = new Rectangle[3]; t[0].aire();</code> provoque :',
   choices:['Rien, aire() renvoie 0','NullPointerException','ArrayIndexOutOfBoundsException','Erreur de compilation'],
   c:1, exp:'Le tableau est alloué mais ses cases valent null : il faut faire <code>t[0] = new Rectangle(...)</code> avant.'},
  {wk:'meth', topic:'Java → UML', q:'<code>class Voiture { private Roue[] roues; Voiture() { roues = new Roue[4]; for(...) roues[i] = new Roue(); } }</code> représente :',
   choices:['Une agrégation','Une composition','Une dépendance','Un héritage'],
   c:1, exp:'Les Roues sont créées DANS le constructeur de Voiture et n\'existent que pour elle : composition (losange plein).'},
  {wk:'meth', topic:'UML → Java', q:'Cardinalité « 1 Bibliotheque ↔ 0..* Livre », navigable de Bibliotheque vers Livre. En Java :',
   choices:['Livre a un attribut Bibliotheque','Bibliotheque a un attribut Livre[] (ou ArrayList), Livre n\'a rien','Les deux classes ont un attribut l\'une vers l\'autre','Livre extends Bibliotheque'],
   c:1, exp:'Cardinalité > 1 = collection ; navigabilité restreinte = seul le côté d\'origine porte l\'attribut.'},
  {wk:'meth', topic:'Écrire une classe', q:'L\'énoncé dit « retirer un montant, refusé si le solde est insuffisant ». La signature la plus adaptée :',
   choices:['<code>void retirer(double m)</code>','<code>boolean retirer(double m)</code>','<code>double retirer()</code>','<code>static void retirer(double m)</code>'],
   c:1, exp:'Un résultat « accepté / refusé » se traduit par un boolean retourné à l\'appelant.'},
  {wk:'meth', topic:'Division entière', q:'<code>int a = 7, b = 2; System.out.println(a / b);</code> affiche :',
   choices:['3.5','3','4','Erreur'],
   c:1, exp:'Division entre deux int = division entière (troncature). Pour 3.5, écrire <code>a / 2.0</code> ou caster.'},
  {wk:'meth', topic:'Classe abstraite', q:'<code>public abstract class Forme { public abstract double aire(); }</code> — que provoque <code>new Forme()</code> ?',
   choices:['Un objet Forme d\'aire 0','Erreur de compilation : classe abstraite non instanciable','Une exception à l\'exécution','null'],
   c:1, exp:'Une classe abstraite ne peut pas être instanciée ; seules ses filles concrètes (qui définissent aire()) le peuvent.'},
  {wk:'meth', topic:'Exceptions', q:'Dans une signature, <code>throws MonException</code> signifie :',
   choices:['La méthode lance toujours MonException','La méthode peut lancer MonException et prévient l\'appelant','La méthode attrape MonException','MonException est une sous-classe de la méthode'],
   c:1, exp:'throws = déclaration ; throw new = lancement effectif ; try/catch = capture chez l\'appelant.'},
  // ================== SEMAINE 5 ==================
  {wk:"s5", topic:"throw / throws", q:"Quel mot-clé, placé dans la <b>signature</b> d'une méthode, annonce qu'elle peut laisser sortir une exception ?",
   choices:["<code>throw</code>","<code>throws</code>","<code>try</code>","<code>catch</code>"],
   c:1, exp:"<code>throws</code> (avec un s) dans la signature ANNONCE ; <code>throw</code> (sans s) dans le corps LANCE un objet exception."},
  {wk:"s5", topic:"Ordre des catch", q:"<code>try {…} catch (Exception e) {…} catch (IOException e) {…}</code> — que se passe-t-il ?",
   choices:["Ça compile, le 2e catch sert pour les IOException","Erreur de compilation : IOException est déjà attrapée","Exception à l'exécution","Le 1er catch est ignoré"],
   c:1, exp:"IOException hérite d'Exception : le 2e catch est inatteignable, javac refuse (« has already been caught »). Du plus précis au plus général."},
  {wk:"s5", topic:"finally et return", q:"<code>int f() { try { return 1; } finally { System.out.print(\"fin \"); } }</code> — l'appel <code>System.out.print(f())</code> affiche :",
   choices:["<code>1</code>","<code>fin 1</code>","<code>1 fin</code>","Erreur de compilation"],
   c:1, exp:"Le finally s'exécute AVANT que la méthode rende la main (même avec un return) : « fin » s'affiche, puis println reçoit 1."},
  {wk:"s5", topic:"finally", q:"Dans quel cas le bloc <code>finally</code> n'est-il PAS exécuté ?",
   choices:["Quand aucune exception n'est levée","Quand le catch fait <code>continue</code>","Quand le try fait <code>return</code>","Quand le catch appelle <code>System.exit(1)</code>"],
   c:3, exp:"System.exit arrête immédiatement la JVM. Dans tous les autres cas, finally s'exécute."},
  {wk:"s5", topic:"Exception contrôlée", q:"Laquelle de ces exceptions est <b>contrôlée</b> (le compilateur oblige à la traiter ou à la déclarer) ?",
   choices:["<code>NullPointerException</code>","<code>ArithmeticException</code>","<code>IOException</code>","<code>NumberFormatException</code>"],
   c:2, exp:"IOException hérite d'Exception sans passer par RuntimeException : elle est contrôlée. Les trois autres sont des RuntimeException."},
  {wk:"s5", topic:"Exception personnalisée", q:"Quelle déclaration crée une exception personnalisée contrôlée ?",
   choices:["<code>class MonErreur implements Exception</code>","<code>class MonErreur extends Exception</code>","<code>class MonErreur throws Exception</code>","<code>exception MonErreur</code>"],
   c:1, exp:"Exception est une CLASSE : on en hérite avec extends."},
  {wk:"s5", topic:"super(msg)", q:"Dans <code>MonErreur(String m) { super(m); }</code>, à quoi sert <code>super(m)</code> ?",
   choices:["À lancer l'exception","À transmettre le message à Exception pour que getMessage() le renvoie","À appeler le catch","Rien, c'est optionnel et sans effet"],
   c:1, exp:"Le constructeur Exception(String) mémorise le message ; sans super(m), getMessage() renvoie null."},
  {wk:"s5", topic:"parseInt", q:"<code>Integer.parseInt(\"12a\")</code> provoque :",
   choices:["12","0","Une NumberFormatException","Une erreur de compilation"],
   c:2, exp:"La chaîne n'est pas un entier valide : NumberFormatException (non contrôlée) à l'exécution."},
  {wk:"s5", topic:"Fichier absent", q:"<code>new Scanner(new File(\"absent.txt\"))</code> sans try/catch ni throws :",
   choices:["Compile, renvoie un Scanner vide","Ne compile pas : FileNotFoundException doit être attrapée ou déclarée","Compile puis NullPointerException","Crée le fichier"],
   c:1, exp:"Le constructeur Scanner(File) déclare throws FileNotFoundException, exception contrôlée."},
  {wk:"s5", topic:"Serializable", q:"Combien de méthodes faut-il écrire pour implémenter <code>Serializable</code> ?",
   choices:["0","1 : <code>serialize()</code>","2 : <code>writeObject</code> et <code>readObject</code>","Autant que d'attributs"],
   c:0, exp:"Serializable est une interface « marqueur » vide : elle autorise seulement la sérialisation."},
  {wk:"s5", topic:"readObject", q:"<code>Client c = ois.readObject();</code> :",
   choices:["Compile et marche","Ne compile pas : readObject renvoie Object, il faut <code>(Client)</code>","Compile mais renvoie toujours null","Ne compile que si Client est abstraite"],
   c:1, exp:"readObject() renvoie Object : cast obligatoire, et gérer IOException + ClassNotFoundException."},
  {wk:"s5", topic:"transient", q:"Après désérialisation, que vaut un attribut <code>transient String motDePasse</code> ?",
   choices:["Sa valeur d'origine","<code>null</code>","<code>\"\"</code>","Ça dépend du fichier"],
   c:1, exp:"transient = non sauvegardé ; il reprend la valeur par défaut de son type (null pour un objet, 0 pour un int)."},
  {wk:"s5", topic:"Flux d'objets", q:"Quelle classe écrit des <b>objets</b> dans un fichier (en l'enveloppant autour d'un FileOutputStream) ?",
   choices:["<code>FileWriter</code>","<code>PrintWriter</code>","<code>ObjectOutputStream</code>","<code>Scanner</code>"],
   c:2, exp:"new ObjectOutputStream(new FileOutputStream(\"f.ser\")) puis writeObject(obj)."},
  {wk:"s5", topic:"NotSerializableException", q:"On sérialise un objet dont la classe n'implémente pas Serializable. Résultat :",
   choices:["Erreur de compilation","NotSerializableException à l'exécution","Le fichier est vide sans erreur","L'objet est converti en String"],
   c:1, exp:"Le compilateur ne vérifie pas : l'erreur arrive à l'exécution, pendant writeObject."},
  {wk:"s5", topic:"split", q:"<code>\"Alice;20;15.5\".split(\";\").length</code> vaut :",
   choices:["1","2","3","14"],
   c:2, exp:"Trois morceaux : \"Alice\", \"20\", \"15.5\" (des String : parseInt / parseDouble ensuite)."},
  {wk:"s5", topic:"Exception non attrapée", q:"Une RuntimeException n'est attrapée nulle part, même pas dans le main. Que se passe-t-il ?",
   choices:["Rien, elle est ignorée","Le programme s'arrête et affiche la trace (stack trace)","Le compilateur refuse","La JVM redémarre le main"],
   c:1, exp:"Elle remonte jusqu'en haut de la pile d'appels : le thread s'arrête avec le message et la trace."},

  // ================== SEMAINE 6 ==================
  {wk:"s6", topic:"Layout par défaut", q:"Layout par défaut du content pane d'une <code>JFrame</code> :",
   choices:["FlowLayout","GridLayout","BorderLayout","Aucun (positions absolues)"],
   c:2, exp:"BorderLayout pour JFrame/JDialog ; FlowLayout pour JPanel."},
  {wk:"s6", topic:"Layout par défaut", q:"Layout par défaut d'un <code>JPanel</code> :",
   choices:["FlowLayout","BorderLayout","GridLayout(1,1)","BoxLayout"],
   c:0, exp:"new JPanel() utilise un FlowLayout : composants à la suite, centrés, taille naturelle."},
  {wk:"s6", topic:"GridLayout", q:"<code>setLayout(new GridLayout(2, 3))</code> puis 5 boutons ajoutés :",
   choices:["2 colonnes, 3 lignes","2 lignes de 3 cases égales, la dernière case vide","5 boutons sur une ligne","Erreur : il faut exactement 6 composants"],
   c:1, exp:"GridLayout(lignes, colonnes) : remplissage de gauche à droite puis de haut en bas, cases identiques."},
  {wk:"s6", topic:"BorderLayout", q:"En BorderLayout, <code>add(b1); add(b2);</code> sans contrainte :",
   choices:["b1 en haut, b2 en bas","Les deux au CENTER : seul b2 est visible","Erreur de compilation","Les deux côte à côte"],
   c:1, exp:"Sans contrainte, add place au CENTER ; le second composant remplace le premier."},
  {wk:"s6", topic:"Abonnement", q:"Quelle méthode abonne un écouteur au clic d'un JButton ?",
   choices:["<code>setListener(this)</code>","<code>addActionListener(this)</code>","<code>actionPerformed(this)</code>","<code>listen(this)</code>"],
   c:1, exp:"bouton.addActionListener(ecouteur) ; sans cette ligne, actionPerformed n'est jamais appelée."},
  {wk:"s6", topic:"ActionListener", q:"Quelle méthode faut-il implémenter pour <code>ActionListener</code> ?",
   choices:["<code>actionPerformed(ActionEvent e)</code>","<code>onClick()</code>","<code>mouseClicked(MouseEvent e)</code>","<code>run()</code>"],
   c:0, exp:"Interface fonctionnelle à une seule méthode : public void actionPerformed(ActionEvent e)."},
  {wk:"s6", topic:"getSource", q:"Dans actionPerformed, <code>e.getSource()</code> renvoie :",
   choices:["Le texte du bouton","Le composant qui a déclenché l'événement","La fenêtre principale","Le nombre de clics"],
   c:1, exp:"On compare ensuite avec == aux boutons pour savoir lequel a été cliqué."},
  {wk:"s6", topic:"Package", q:"Dans quel package se trouvent <code>ActionListener</code> et <code>ActionEvent</code> ?",
   choices:["<code>javax.swing</code>","<code>java.awt.event</code>","<code>java.util</code>","<code>java.lang</code>"],
   c:1, exp:"import java.awt.event.*; (les composants Swing sont dans javax.swing)."},
  {wk:"s6", topic:"EXIT_ON_CLOSE", q:"Sans <code>setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE)</code>, fermer la fenêtre :",
   choices:["Termine le programme","La cache mais le programme continue de tourner","Provoque une exception","Est impossible"],
   c:1, exp:"Le comportement par défaut est HIDE_ON_CLOSE : la JVM reste lancée."},
  {wk:"s6", topic:"pack", q:"<code>pack()</code> :",
   choices:["Compresse l'application","Ajuste la taille de la fenêtre à la taille préférée de ses composants","Ferme la fenêtre","Range les composants par ordre alphabétique"],
   c:1, exp:"Alternative à setSize : la fenêtre prend juste la place nécessaire."},
  {wk:"s6", topic:"Conteneurs", q:"Lequel est un conteneur <b>racine</b> (fenêtre de premier niveau) ?",
   choices:["<code>JPanel</code>","<code>JButton</code>","<code>JFrame</code>","<code>JLabel</code>"],
   c:2, exp:"JFrame, JDialog, JWindow sont des conteneurs racines ; JPanel est un conteneur intermédiaire."},
  {wk:"s6", topic:"Adapter", q:"À quoi sert <code>WindowAdapter</code> ?",
   choices:["À redimensionner la fenêtre","À fournir toutes les méthodes de WindowListener à vide pour n'en redéfinir qu'une","À convertir AWT en Swing","À ouvrir une deuxième fenêtre"],
   c:1, exp:"WindowListener a 7 méthodes : en héritant de WindowAdapter on ne redéfinit que windowClosing par exemple."},
  {wk:"s6", topic:"Saisie", q:"Pour calculer avec le nombre tapé dans un <code>JTextField tf</code> :",
   choices:["<code>int n = tf.getText();</code>","<code>int n = Integer.parseInt(tf.getText());</code>","<code>int n = (int) tf;</code>","<code>int n = tf.getInt();</code>"],
   c:1, exp:"getText() renvoie une String : conversion avec Integer.parseInt (NumberFormatException si ce n'est pas un nombre)."},
  {wk:"s6", topic:"Afficher un nombre", q:"<code>label.setText(42);</code> :",
   choices:["Affiche 42","Erreur de compilation : setText attend une String","Affiche \"42.0\"","Exception à l'exécution"],
   c:1, exp:"Écrire label.setText(String.valueOf(42)) ou label.setText(\"\" + 42)."},
  {wk:"s6", topic:"Swing ou AWT", q:"Quel composant appartient à <b>Swing</b> ?",
   choices:["<code>Button</code>","<code>Frame</code>","<code>JButton</code>","<code>Label</code>"],
   c:2, exp:"Les composants Swing commencent par J (JButton, JFrame, JLabel) ; Button, Frame, Label sont AWT."},
  {wk:"s6", topic:"Message", q:"Pour afficher une erreur dans une petite fenêtre :",
   choices:["<code>System.err.println</code>","<code>JOptionPane.showMessageDialog(this, \"Erreur\")</code>","<code>new JError(\"Erreur\")</code>","<code>throw new JFrame(\"Erreur\")</code>"],
   c:1, exp:"JOptionPane.showMessageDialog(parent, message, titre, JOptionPane.ERROR_MESSAGE) : utile au TP6 pour les exceptions."},

  // ================== SEMAINE 7 ==================
  {wk:"s7", topic:"MVC", q:"MVC signifie :",
   choices:["Modèle – Vue – Contrôleur","Méthode – Variable – Classe","Main – View – Code","Module – Version – Compilation"],
   c:0, exp:"Patron d'architecture qui sépare les données (Modèle), l'affichage (Vue) et la gestion des actions (Contrôleur)."},
  {wk:"s7", topic:"Rôles", q:"Où placer la règle « refuser une commande si le solde est insuffisant » ?",
   choices:["Dans la Vue","Dans le Contrôleur","Dans le Modèle","Dans le main"],
   c:2, exp:"Règle métier = Modèle ; il lève l'exception, le contrôleur l'attrape, la vue affiche le message."},
  {wk:"s7", topic:"Rôles", q:"En Swing + MVC, quelle classe implémente <code>ActionListener</code> ?",
   choices:["Le Modèle","Le Contrôleur","Aucune","La classe Plat"],
   c:1, exp:"Le contrôleur écoute les composants de la vue et traduit chaque action en appel au modèle."},
  {wk:"s7", topic:"Modèle", q:"Qu'est-ce que le Modèle ne doit PAS contenir ?",
   choices:["Des attributs","Des exceptions","Des composants Swing (JLabel, JOptionPane…)","Des méthodes de calcul"],
   c:2, exp:"Le modèle doit fonctionner (et être testé) sans interface graphique."},
  {wk:"s7", topic:"Observateur", q:"Quel patron permet au Modèle de prévenir la Vue sans la connaître ?",
   choices:["Singleton","Observateur (listeners / abonnés)","Fabrique","Adaptateur"],
   c:1, exp:"Le modèle garde une liste d'abonnés (interface) et appelle leur méthode à chaque changement."},
  {wk:"s7", topic:"Cycle", q:"Ordre correct du cycle MVC après un clic :",
   choices:["Modèle → Vue → Contrôleur","Vue → Contrôleur → Modèle → Vue","Contrôleur → Vue → Modèle","Vue → Modèle → Contrôleur"],
   c:1, exp:"La vue reçoit le clic, le contrôleur appelle le modèle, le modèle notifie, la vue se redessine."},
  {wk:"s7", topic:"Avantages", q:"Un avantage direct du MVC :",
   choices:["Le programme s'exécute plus vite","On peut tester le modèle sans fenêtre et changer la vue sans toucher aux calculs","On n'a plus besoin d'exceptions","On évite l'héritage"],
   c:1, exp:"Séparation des responsabilités : maintenance, tests, réutilisation, travail en équipe."},
  {wk:"s7", topic:"Plusieurs vues", q:"Un même modèle peut-il avoir plusieurs vues ?",
   choices:["Non, une seule","Oui, chaque vue s'abonne au modèle","Seulement si elles héritent l'une de l'autre","Seulement en console"],
   c:1, exp:"Exemple : une fenêtre Swing et un affichage console abonnés au même modèle restent synchronisés."},
  {wk:"s7", topic:"Vue", q:"Le rôle de la Vue :",
   choices:["Afficher les données et exposer ses composants","Enregistrer les données dans un fichier","Vérifier les règles métier","Créer le contrôleur"],
   c:0, exp:"Elle affiche, fournit des getters (valeur saisie, bouton) et une méthode de rafraîchissement."},
  {wk:"s7", topic:"Exceptions", q:"En MVC, une exception métier (solde insuffisant) est typiquement :",
   choices:["Levée par la Vue, attrapée par le Modèle","Levée par le Modèle, attrapée par le Contrôleur qui demande à la Vue d'afficher un message","Ignorée","Levée par le main"],
   c:1, exp:"Chaque couche garde son rôle : le modèle signale, le contrôleur décide, la vue montre."},
  {wk:"s7", topic:"Dépendances", q:"Qui connaît qui ?",
   choices:["Le modèle connaît la vue et le contrôleur","Le contrôleur connaît la vue et le modèle ; le modèle ne connaît que des abonnés abstraits","La vue crée le modèle et le contrôleur","Personne ne se connaît"],
   c:1, exp:"Le modèle est la couche la plus indépendante : il ne dépend ni de Swing ni du contrôleur."},
  {wk:"s7", topic:"Organisation", q:"Une organisation de packages typique du TP7 :",
   choices:["<code>a</code>, <code>b</code>, <code>c</code>","<code>modele</code>, <code>vue</code>, <code>controleur</code>","Tout dans le package par défaut","<code>java.mvc</code>"],
   c:1, exp:"Un package par couche + un Main qui crée et relie M, V et C."},
];
